/*
 *
 * Automatically generated file; DO NOT EDIT.
 * Linux/arm64 4.4.302 Kernel Configuration
 *
 */
#ifndef __SYNO_AUTOCONF_H__
#define __SYNO_AUTOCONF_H__
#define CONFIG_SYNO_MAX_READAHEAD_SIZE 1024
#define CONFIG_SYNO_SATA_RETRY_TIMES 5
#define CONFIG_SYNO_PWRPIN_ENCODE_LEN 8
#define CONFIG_SYNO_ISCSI_DEVICE_PREFIX "iscsi"
#define CONFIG_SYNO_USB_POWER_OFF_TIME 100
#define CONFIG_SYNO_MAX_SATA_ID 4
#define CONFIG_SYNO_DEFAULT_HUNG_TASK_WARNINGS 300
#define CONFIG_SYNO_MAX_INTERNAL_DISK 24
#define CONFIG_SYNO_USB_POWER_ON_TIME 100
#define CONFIG_SYNO_DEFAULT_HUNG_TASK_RESET_PERIOD 360
#define CONFIG_SYNO_HUB_POWER_CYCLE_EXTRA_DELAY_TIME 50
#define CONFIG_SYNO_USB_VBUS_NUM_GPIO 1
#define CONFIG_SYNO_PORT_SIGN "S"
#define CONFIG_SYNO_SOFTLOCKUP_COUNTER_MAX 10
#define CONFIG_SYNO_IO_ERROR_LIMIT_MSG_SHIFT 6
#define CONFIG_SYNO_USB_NUM_CASTRATED_XHC 2
#define CONFIG_SYNO_SATA_DEVICE_PREFIX "sata"
#endif /* __SYNO_AUTOCONF_H__ */